//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendance_Id { get; set; }
        public Nullable<int> subject_Id { get; set; }
        public string subject_Name { get; set; }
        public string student_Name { get; set; }
        public string grade { get; set; }
        public string section { get; set; }
        public string status { get; set; }
        public Nullable<int> student_Id { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Student Student { get; set; }
    }
}
